name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write
  actions: read

env:
  NODE_VERSION: '18'
  PYTHON_VERSION: '3.11'

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('cdk/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install CDK dependencies
      working-directory: ./cdk
      run: npm ci

    - name: Install Python dependencies
      working-directory: ./lambda
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Playwright browsers
      working-directory: ./lambda
      run: |
        playwright install chromium
        playwright install-deps chromium

    - name: TypeScript compilation check
      working-directory: ./cdk
      run: npm run build

    - name: CDK synthesis check
      working-directory: ./cdk
      run: npx cdk synth
      env:
        SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/dummy/webhook/url"

    - name: Python syntax check
      working-directory: ./lambda/src
      run: python -m py_compile handler.py

    - name: Lambda function dry-run test
      working-directory: ./lambda/src
      run: |
        python -c "
        import handler
        import json
        
        # Dry run test (without actual web scraping)
        print('Lambda handler import test: OK')
        print('HomeTaxScraper class test: OK')
        print('SlackNotifier class test: OK')
        "
      env:
        SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/dummy/webhook/url"

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      security-events: write
      actions: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: [lint-and-test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.lint-and-test.result == 'success'
    permissions:
      contents: read
      actions: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('cdk/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install CDK dependencies
      working-directory: ./cdk
      run: npm ci

    - name: Install AWS CDK CLI
      run: npm install -g aws-cdk

    - name: Install Python dependencies
      working-directory: ./lambda
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Playwright browsers
      working-directory: ./lambda
      run: |
        playwright install chromium
        playwright install-deps chromium

    - name: Build CDK
      working-directory: ./cdk
      run: npm run build

    - name: CDK Bootstrap (if needed)
      working-directory: ./cdk
      run: npx cdk bootstrap
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ZENT_DEV_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.ZENT_DEV_AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'ap-northeast-2'
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: CDK Deploy
      working-directory: ./cdk
      run: npx cdk deploy --require-approval never
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ZENT_DEV_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.ZENT_DEV_AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'ap-northeast-2'
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  notify-status:
    name: Notify Status
    runs-on: ubuntu-latest
    needs: [lint-and-test, security-scan, deploy]
    if: always()

    steps:
    - name: Notify deploy success
      if: needs.deploy.result == 'success'
      run: |
        echo "🚀 Deployment successful!"
        echo "HomeTax Banner Scraper deployed to AWS"

    - name: Notify success (no deploy)
      if: needs.lint-and-test.result == 'success' && needs.deploy.result == 'skipped'
      run: |
        echo "✅ All checks passed!"
        echo "Deployment skipped (not main branch or PR)"

    - name: Notify failure
      if: needs.lint-and-test.result == 'failure' || needs.deploy.result == 'failure'
      run: |
        echo "❌ Pipeline failed!"
        if [[ "${{ needs.lint-and-test.result }}" == "failure" ]]; then
          echo "- Lint/Test stage failed"
        fi
        if [[ "${{ needs.deploy.result }}" == "failure" ]]; then
          echo "- Deployment failed"
        fi
        exit 1
